name: Build and deploy PHP app to Azure Web App - canama-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --optimize-autoloader --no-dev

      - name: Cache configuration
        run: php artisan config:cache

      - name: Cache routes
        run: php artisan route:cache

      - name: Cache views
        run: php artisan view:cache

      - name: Remove any existing zip files
        run: rm -f php-app.zip

      - name: Zip artifact for deployment
        run: zip -r php-app.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: php-app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'canama-backend'
          slot-name: 'Production'
<<<<<<< HEAD
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
=======
          package: 'php-app.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3EA96C47235C47B6A72C8517FF69BE00 }}
>>>>>>> 860fef596cb98ea7d50a9945e1fef8bc083254b4
